name: BenGulley
favicon: null
layout_spectrum: 0
typography_spectrum: 0.25302
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#796f6e'
    - '#682514'
    - '#c7ac9f'
    - '#fddcbe'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
