name: BenGulley
favicon: null
layout_spectrum: 0.11788574373349547
typography_spectrum: 0.9200394307263196
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7170484564267099
  lightness: 0.7470088873524219
  saturation: 0.021627867594361305
  rhythmicContrast: 0.3016885742545128
purpose: []
