name: BenGulley
favicon: null
layout_spectrum: 0.35988
typography_spectrum: 0.3498
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#494949'
    - '#797979'
    - '#a7a7a7'
    - '#d0d0d0'
  brandStrength: 0.4375
  lightness: 0.625
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
